"""
calibrate_ph.py
---------------
Interactive two-point pH calibration script.

Run this script BEFORE your first use of the pH sensor and any time
the sensor has been stored dry or readings seem off.

What you need:
  - pH 7.0 buffer solution (neutral, used as point 1)
  - pH 4.0 buffer solution (acidic, used as point 2)
  - A cup of clean water for rinsing between measurements

How to run:
  python3 calibrate_ph.py

The script will walk you through the process step by step and save
the calibration values to config.py automatically.

Hardware assumed:
  - ADS1115 ADC connected via I2C (SDA → GPIO2, SCL → GPIO3)
  - pH sensor analog output → ADS1115 channel A0
"""

import time
import board
import busio
import adafruit_ads1x15.ads1115 as ADS
from adafruit_ads1x15.analog_in import AnalogIn


# ── ADC setup ────────────────────────────────────────────────────────────────
i2c = busio.I2C(board.SCL, board.SDA)
ads = ADS.ADS1115(i2c)
ads.gain = 1          # ±4.096V range — appropriate for pH sensor output
ph_channel = AnalogIn(ads, ADS.P3)   # pH sensor on channel A3


def read_average_voltage(samples: int = 20, delay: float = 0.1) -> float:
    """
    Read the pH sensor voltage multiple times and return the average.
    Averaging smooths out electrical noise for a more stable calibration point.

    Args:
        samples: number of readings to average (default 20)
        delay:   seconds between each reading (default 0.1)

    Returns:
        Average voltage in volts (float)
    """
    readings = []
    for _ in range(samples):
        readings.append(ph_channel.voltage)
        time.sleep(delay)
    average = sum(readings) / len(readings)
    return average


def save_calibration(v7: float, v4: float) -> None:
    """
    Append or overwrite the calibration constants in config.py.
    If config.py does not exist yet, it creates a minimal one.

    Args:
        v7: voltage measured in pH 7.0 buffer solution
        v4: voltage measured in pH 4.0 buffer solution
    """
    try:
        with open("config.py", "r") as f:
            lines = f.readlines()
    except FileNotFoundError:
        lines = []

    # Remove any existing PH_VOLTAGE_AT_7 / PH_VOLTAGE_AT_4 lines
    lines = [l for l in lines if not l.startswith("PH_VOLTAGE_AT_7") and
                                  not l.startswith("PH_VOLTAGE_AT_4")]

    # Append fresh calibration values
    lines.append(f"\n# pH calibration — generated by calibrate_ph.py\n")
    lines.append(f"PH_VOLTAGE_AT_7 = {v7:.6f}   # volts at pH 7.0 buffer\n")
    lines.append(f"PH_VOLTAGE_AT_4 = {v4:.6f}   # volts at pH 4.0 buffer\n")

    with open("config.py", "w") as f:
        f.writelines(lines)

    print("\n  Saved to config.py:")
    print(f"    PH_VOLTAGE_AT_7 = {v7:.6f}")
    print(f"    PH_VOLTAGE_AT_4 = {v4:.6f}")


def verify_calibration(v7: float, v4: float) -> None:
    """
    After calibration, read the current voltage and show what pH it maps to.
    Lets you do a quick sanity check while the sensor is still in a buffer.

    Args:
        v7: calibrated voltage at pH 7
        v4: calibrated voltage at pH 4
    """
    print("\n── Verification ─────────────────────────────────────────────────")
    print("  Leave the sensor in the pH 4.0 solution (or try clean water).")
    print("  Press Enter to take a verification reading.")
    input()

    voltage = read_average_voltage()
    # Two-point linear interpolation formula
    ph = 7.0 + (v7 - voltage) * (7.0 - 4.0) / (v7 - v4)

    print(f"  Voltage read  : {voltage:.4f} V")
    print(f"  Calculated pH : {ph:.2f}")
    print()

    if abs(ph - 4.0) < 0.3:
        print("  ✓  Reading looks correct — within 0.3 of pH 4.0.")
    elif abs(ph - 7.0) < 0.3:
        print("  ✓  Reading looks correct — within 0.3 of pH 7.0.")
    else:
        print("  ⚠  Reading seems off. Consider repeating calibration with")
        print("     fresh buffer solutions and a clean, dry sensor tip.")


# ── main calibration flow ─────────────────────────────────────────────────────
def main():
    print()
    print("══════════════════════════════════════════════════════════════════")
    print("  pH Sensor Two-Point Calibration")
    print("══════════════════════════════════════════════════════════════════")
    print()
    print("  This script performs a two-point calibration using:")
    print("    Point 1 — pH 7.0 buffer (neutral)")
    print("    Point 2 — pH 4.0 buffer (acidic)")
    print()
    print("  Tips for accurate results:")
    print("    • Rinse the sensor tip with clean water between buffer solutions")
    print("    • Pat dry gently with a paper towel — do not rub")
    print("    • Let the sensor stabilise in each solution for ~30 seconds")
    print("      before recording")
    print()

    # ── Point 1: pH 7.0 ──────────────────────────────────────────────────────
    print("── Step 1 of 2 — pH 7.0 buffer ──────────────────────────────────")
    print("  Place the sensor in the pH 7.0 buffer solution.")
    print("  Press Enter when ready to start reading.")
    input()

    print("  Stabilising... (reading voltage for 30 seconds)")
    print("  Live readings:")

    # Show live readings while stabilising so the user can watch drift settle
    start = time.time()
    while time.time() - start < 30:
        v = ph_channel.voltage
        elapsed = int(time.time() - start)
        bar = "█" * (elapsed // 3)
        print(f"  {elapsed:>3}s  {v:.4f} V  {bar:<10}", end="\r")
        time.sleep(1)

    print()
    print("  Capturing average voltage (20 samples)...")
    v7 = read_average_voltage(samples=20, delay=0.1)
    print(f"  ✓  pH 7.0 voltage recorded: {v7:.4f} V")

    # ── Rinse ────────────────────────────────────────────────────────────────
    print()
    print("── Rinse ─────────────────────────────────────────────────────────")
    print("  Remove sensor from pH 7.0 solution.")
    print("  Rinse the tip with clean water and pat dry gently.")
    print("  Press Enter when ready to continue.")
    input()

    # ── Point 2: pH 4.0 ──────────────────────────────────────────────────────
    print("── Step 2 of 2 — pH 4.0 buffer ──────────────────────────────────")
    print("  Place the sensor in the pH 4.0 buffer solution.")
    print("  Press Enter when ready to start reading.")
    input()

    print("  Stabilising... (reading voltage for 30 seconds)")
    print("  Live readings:")

    start = time.time()
    while time.time() - start < 30:
        v = ph_channel.voltage
        elapsed = int(time.time() - start)
        bar = "█" * (elapsed // 3)
        print(f"  {elapsed:>3}s  {v:.4f} V  {bar:<10}", end="\r")
        time.sleep(1)

    print()
    print("  Capturing average voltage (20 samples)...")
    v4 = read_average_voltage(samples=20, delay=0.1)
    print(f"  ✓  pH 4.0 voltage recorded: {v4:.4f} V")

    # ── Sanity check ─────────────────────────────────────────────────────────
    print()
    print("── Calibration summary ───────────────────────────────────────────")
    print(f"  pH 7.0 buffer  →  {v7:.4f} V")
    print(f"  pH 4.0 buffer  →  {v4:.4f} V")
    print(f"  Voltage difference: {abs(v7 - v4):.4f} V")
    print()

    if abs(v7 - v4) < 0.1:
        print("  ⚠  WARNING: Voltage difference between the two points is very small.")
        print("     This may indicate a faulty sensor, incorrect wiring, or")
        print("     contaminated buffer solutions. Consider repeating.")
        print()

    # ── Save ─────────────────────────────────────────────────────────────────
    print("  Saving calibration values to config.py...")
    save_calibration(v7, v4)

    # ── Verify ───────────────────────────────────────────────────────────────
    verify = input("\n  Run a verification reading now? (y/n): ").strip().lower()
    if verify == "y":
        verify_calibration(v7, v4)

    print()
    print("══════════════════════════════════════════════════════════════════")
    print("  Calibration complete.")
    print("  You can now run main.py to start collecting readings.")
    print("══════════════════════════════════════════════════════════════════")
    print()


if __name__ == "__main__":
    main()