# Generated by Django 4.2.30 on 2026-05-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when the reading was recorded.')),
                ('ph', models.FloatField(blank=True, help_text='pH value (0–14 scale).', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='Water temperature in °C.', null=True)),
                ('tds', models.FloatField(blank=True, help_text='Total dissolved solids in mg/L.', null=True)),
                ('turbidity', models.FloatField(blank=True, help_text='Turbidity in NTU.', null=True)),
                ('source', models.CharField(default='pi-01', help_text="Device identifier (e.g. 'pi-01').", max_length=50)),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'verbose_name_plural': 'Sensor Readings',
                'ordering': ['-timestamp'],
            },
        ),
    ]
