# Generated by Django 4.2.30 on 2026-05-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='alert_level',
            field=models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('WARNING', 'Warning'), ('INFO', 'Info')], help_text='Alert severity: CRITICAL, WARNING, or INFO.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='alert_sent',
            field=models.BooleanField(default=False, help_text='Whether an SNS notification was sent for this reading.'),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='anomaly_score',
            field=models.FloatField(blank=True, help_text='ML reconstruction error score (higher = more anomalous).', null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='is_anomaly',
            field=models.BooleanField(blank=True, help_text='True if the ML model flagged this reading as anomalous.', null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='ml_confidence',
            field=models.CharField(blank=True, help_text="ML confidence level: 'high', 'medium', or 'low'.", max_length=10, null=True),
        ),
    ]
