# Generated by Django 4.2.30 on 2026-05-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_sensorreading_alert_level_sensorreading_alert_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='is_anomaly_ph',
            field=models.BooleanField(default=False, help_text='True if the ML model flagged pH as anomalous.'),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='is_anomaly_tds',
            field=models.BooleanField(default=False, help_text='True if the ML model flagged TDS as anomalous.'),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='is_anomaly_temp',
            field=models.BooleanField(default=False, help_text='True if the ML model flagged temperature as anomalous.'),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='is_anomaly_turb',
            field=models.BooleanField(default=False, help_text='True if the ML model flagged turbidity as anomalous.'),
        ),
    ]
